# Different voice options [:np] [:nb] [:nh] [:nd] [:nf] [:nu] [:nr] [:nw] [:nk]

# How much to shift pitches by (DECTALK Pitches not the same as midi, should be 48 off or so)
noteOffset: -48

# Words are broken up into phonemes, the playback lengths of which must be specified in code
# This is calculated by setting a standard fraction of each word to dedicate to consonants
# Also specify min and max length in milliseconds for each consonant to prevent weird issues
consonantFractionTarget: 0.15
consonantMinMs: 5
consonantMaxMs: 75

# Set specific settings for each output track. LYRICS_FILENAME and TRACK_FILENAME
# default to the output track name if omitted.
Tracks:
  Vocals:
    DEC_SETUP: "[:np][:dv hs 125]"
    VOLUME_ADJUST_DB: 5.0

    SPECTROGRAM:
      COLOR_HSB: [347, 79, 100]
      POSITION: [0.333, 0.333, 0]
      LABEL: "Lead"
      LABEL_ENABLED: false
      LABEL_POSITION: "top-left"
      LABEL_SHOW_VOICE: false
      LABEL_SHOW_HEAD_SIZE: false
      CURRENT_WORD_ENABLED: false
      CURRENT_WORD_POSITION: "bottom-center"

  Alto:
    DEC_SETUP: "[:nk][:dv hs 75]"
    VOLUME_ADJUST_DB: 5.0

    SPECTROGRAM:
      COLOR_HSB: [328, 70, 97]
      POSITION: [0.333, 0.666, 0.333]
      LABEL: "Alto"
      LABEL_ENABLED: false
      LABEL_POSITION: "top-left"
      LABEL_SHOW_VOICE: false
      LABEL_SHOW_HEAD_SIZE: false
      CURRENT_WORD_ENABLED: false
      CURRENT_WORD_POSITION: "bottom-center"

  Tenor1:
    DEC_SETUP: "[:np][:dv hs 100]"
    VOLUME_ADJUST_DB: 5.0
    LYRICS_FILENAME: 'Tenor'
    TRACK_FILENAME: 'Tenor1'

    SPECTROGRAM:
      COLOR_HSB: [339, 63, 53]
      POSITION: [0.333, 0.666, 0.666]
      LABEL: "Tenor 1"
      LABEL_ENABLED: false
      LABEL_POSITION: "top-left"
      LABEL_SHOW_VOICE: false
      LABEL_SHOW_HEAD_SIZE: false
      CURRENT_WORD_ENABLED: false
      CURRENT_WORD_POSITION: "bottom-center"

  Tenor2:
    DEC_SETUP: "[:np][:dv hs 111]"
    VOLUME_ADJUST_DB: 5.0
    LYRICS_FILENAME: 'Tenor'
    TRACK_FILENAME: 'Tenor2'

    SPECTROGRAM:
      COLOR_HSB: [322, 59, 65]
      POSITION: [0.333, 0.333, 0.666]
      LABEL: "Tenor 2"
      LABEL_ENABLED: false
      LABEL_POSITION: "top-left"
      LABEL_SHOW_VOICE: false
      LABEL_SHOW_HEAD_SIZE: false
      CURRENT_WORD_ENABLED: false
      CURRENT_WORD_POSITION: "bottom-center"

  Bass:
    DEC_SETUP: "[:np]"
    VOLUME_ADJUST_DB: 5.0
    SPECTROGRAM:
      COLOR_HSB: [301, 49, 41]
      POSITION: [0.333, 0, 0.666]
      LABEL: "Bass"
      LABEL_ENABLED: false
      LABEL_POSITION: "top-left"
      LABEL_SHOW_VOICE: false
      LABEL_SHOW_HEAD_SIZE: false
      CURRENT_WORD_ENABLED: false
      CURRENT_WORD_POSITION: "bottom-center"
