# Different voice options [:np] [:nb] [:nh] [:nd] [:nf] [:nu] [:nr] [:nw] [:nk]

# How much to shift pitches by (DECTALK Pitches not the same as midi, should be 48 off or so)
noteOffset: -48

# Words are broken up into phonemes, the playback lengths of which must be specified in code
# This is calculated by setting a standard fraction of each word to dedicate to consonants
# Also specify min and max length in milliseconds for each consonant to prevent weird issues
consonantFractionTarget: 0.15
consonantMinMs: 5
consonantMaxMs: 75

# Set specific settings for each output track. LYRICS_FILENAME and TRACK_FILENAME
# default to the output track name if omitted.
Tracks:
  Vocals:
    DEC_SETUP: "[:np][:dv hs 125]"
    VOLUME_ADJUST_DB: 2

    SPECTROGRAM:
      COLOR_HSB: [347, 79, 100]
      POSITION: [0.5, 0, 0]
      LABEL: "Lead"
      LABEL_ENABLED: true
      LABEL_POSITION: "top-left"
      LABEL_SHOW_VOICE: false
      LABEL_SHOW_HEAD_SIZE: false
      LABEL_FONT: "serif"
      LABEL_FONT_SIZE_PERCENT: 7
      CURRENT_WORD_ENABLED: true
      CURRENT_WORD_POSITION: "bottom-center"
      CURRENT_WORD_FONT: "mono"
      CURRENT_WORD_FONT_SIZE_PERCENT: 10
      CURRENT_WORD_USE_TRACK_COLOR: true

    PITCH_SHIFT: 0
    OCTAVE_BOOST: 0
    PITCH_WRAP_SHIFT: null
    IGNORE_MIDI_VELOCITY: true
    VELOCITY_VOLUME_SCALE_DB: 0
    STEM_PEAK_CEILING_DBFS: -3
    GAP_MEND_MS: 0
    MINIMUM_NOTE_DURATION_MS: 0
  Alto:
    DEC_SETUP: "[:nk][:dv hs 75]"
    VOLUME_ADJUST_DB: 0

    SPECTROGRAM:
      COLOR_HSB: [328, 70, 97]
      POSITION: [0.5, 0.5, 0]
      LABEL: "Alto"
      LABEL_ENABLED: true
      LABEL_POSITION: "top-left"
      LABEL_SHOW_VOICE: false
      LABEL_SHOW_HEAD_SIZE: false
      LABEL_FONT: "choir"
      LABEL_FONT_SIZE_PERCENT: 7
      CURRENT_WORD_ENABLED: false
      CURRENT_WORD_POSITION: "bottom-center"
      CURRENT_WORD_FONT: "choir"
      CURRENT_WORD_FONT_SIZE_PERCENT: 10
      CURRENT_WORD_USE_TRACK_COLOR: false

    PITCH_SHIFT: 0
    OCTAVE_BOOST: 0
    PITCH_WRAP_SHIFT: null
    IGNORE_MIDI_VELOCITY: true
    VELOCITY_VOLUME_SCALE_DB: 0
    STEM_PEAK_CEILING_DBFS: -2
    GAP_MEND_MS: 0
  Tenor1:
    DEC_SETUP: "[:np][:dv hs 100]"
    VOLUME_ADJUST_DB: 3
    LYRICS_FILENAME: 'Tenor'
    TRACK_FILENAME: 'Tenor1'

    SPECTROGRAM:
      COLOR_HSB: [339, 63, 53]
      POSITION: [0.25, 0.503, 0.5]
      LABEL: "Tenor 1"
      LABEL_ENABLED: true
      LABEL_POSITION: "top-left"
      LABEL_SHOW_VOICE: false
      LABEL_SHOW_HEAD_SIZE: false
      LABEL_FONT: "choir"
      LABEL_FONT_SIZE_PERCENT: 7
      CURRENT_WORD_ENABLED: false
      CURRENT_WORD_POSITION: "bottom-center"
      CURRENT_WORD_FONT: "choir"
      CURRENT_WORD_FONT_SIZE_PERCENT: 10
      CURRENT_WORD_USE_TRACK_COLOR: false

    PITCH_SHIFT: 0
    OCTAVE_BOOST: 0
    PITCH_WRAP_SHIFT: null
    IGNORE_MIDI_VELOCITY: true
    VELOCITY_VOLUME_SCALE_DB: 0
    STEM_PEAK_CEILING_DBFS: -1
    GAP_MEND_MS: 0
  Tenor2:
    DEC_SETUP: "[:np][:dv hs 111]"
    VOLUME_ADJUST_DB: 3
    LYRICS_FILENAME: 'Tenor'
    TRACK_FILENAME: 'Tenor2'

    SPECTROGRAM:
      COLOR_HSB: [322, 59, 65]
      POSITION: [0.25, 0.75, 0.75]
      LABEL: "Tenor 2"
      LABEL_ENABLED: true
      LABEL_POSITION: "top-right"
      LABEL_SHOW_VOICE: false
      LABEL_SHOW_HEAD_SIZE: false
      LABEL_FONT: "choir"
      LABEL_FONT_SIZE_PERCENT: 7
      CURRENT_WORD_ENABLED: false
      CURRENT_WORD_POSITION: "bottom-center"
      CURRENT_WORD_FONT: "choir"
      CURRENT_WORD_FONT_SIZE_PERCENT: 10
      CURRENT_WORD_USE_TRACK_COLOR: false

    PITCH_SHIFT: 0
    OCTAVE_BOOST: 0
    PITCH_WRAP_SHIFT: null
    IGNORE_MIDI_VELOCITY: true
    VELOCITY_VOLUME_SCALE_DB: 0
    STEM_PEAK_CEILING_DBFS: -1
    GAP_MEND_MS: 0
  Bass:
    DEC_SETUP: "[:np]"
    VOLUME_ADJUST_DB: 0
    SPECTROGRAM:
      COLOR_HSB: [0, 99, 64]
      POSITION: [0.5, 0, 0.5]
      LABEL: "Bass"
      LABEL_ENABLED: true
      LABEL_POSITION: "top-left"
      LABEL_SHOW_VOICE: false
      LABEL_SHOW_HEAD_SIZE: false
      LABEL_FONT: "serif"
      LABEL_FONT_SIZE_PERCENT: 7
      CURRENT_WORD_ENABLED: false
      CURRENT_WORD_POSITION: "bottom-center"
      CURRENT_WORD_FONT: "choir"
      CURRENT_WORD_FONT_SIZE_PERCENT: 10
      CURRENT_WORD_USE_TRACK_COLOR: false

    PITCH_SHIFT: 0
    OCTAVE_BOOST: 0
    PITCH_WRAP_SHIFT: null
    IGNORE_MIDI_VELOCITY: true
    VELOCITY_VOLUME_SCALE_DB: 0
    STEM_PEAK_CEILING_DBFS: -1
    GAP_MEND_MS: 0
