"""Create and analyze a controlled DECtalk head-size/pitch loudness reference.

The generated song has one identical monophonic chromatic track per head size.
All gain compensation is disabled so the rendered stems expose the native
interaction between ``[:dv hs ...]`` and pitch. Render it with::

    .\.venv\Scripts\python.exe choir.py HeadSizePitchReference

Then write a per-note CSV from the rendered stems with::

    .\.venv\Scripts\python.exe tools\create_head_size_pitch_reference.py --analyze
"""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path

from mido import Message, MetaMessage, MidiFile, MidiTrack, bpm2tempo
from pydub import AudioSegment


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SONG_NAME = "HeadSizePitchReference"
HEAD_SIZES = (65, 80, 95, 110, 125, 140)
FIRST_MIDI_NOTE = 48  # C3, DECtalk pitch 0 with noteOffset -48.
NOTE_COUNT = 37  # C3 through C6, inclusive: the configured DECtalk pitch range.
NOTE_DURATION_MS = 1_000
TICKS_PER_BEAT = 480
NOTE_TICKS = TICKS_PER_BEAT * 2  # 120 BPM: one second per note.
TEMPO = bpm2tempo(120)
STEM_LEAD_IN_MS = 1_000  # choir.py's stem assembly lead-in.
ANALYSIS_ATTACK_SKIP_MS = 120
ANALYSIS_RELEASE_SKIP_MS = 80


def _track_name(head_size: int) -> str:
    return f"Head{head_size}"


def _song_paths(song_name: str) -> tuple[Path, Path, Path, Path]:
    song_dir = REPO_ROOT / "songs" / song_name
    inputs_dir = song_dir / "inputs"
    lyrics_dir = inputs_dir / "lyrics"
    return song_dir, inputs_dir, lyrics_dir, inputs_dir / f"{song_name}.mid"


def _write_midi(path: Path) -> None:
    midi = MidiFile(ticks_per_beat=TICKS_PER_BEAT)
    notes = range(FIRST_MIDI_NOTE, FIRST_MIDI_NOTE + NOTE_COUNT)
    for head_size in HEAD_SIZES:
        track = MidiTrack()
        midi.tracks.append(track)
        track.append(MetaMessage("track_name", name=_track_name(head_size), time=0))
        track.append(MetaMessage("set_tempo", tempo=TEMPO, time=0))
        for midi_note in notes:
            track.append(Message("note_on", note=midi_note, velocity=96, time=0))
            track.append(Message("note_off", note=midi_note, velocity=0, time=NOTE_TICKS))
        track.append(MetaMessage("end_of_track", time=0))
    midi.save(path)


def _write_lyrics(path: Path) -> None:
    # ``duw`` is a validated direct phoneme syllable; one token maps to one note.
    path.write_text(" ".join("`duw" for _ in range(NOTE_COUNT)) + "\n", encoding="ascii")


def _write_settings(path: Path) -> None:
    tracks = "".join(
        "  {name}:\n"
        "    LYRICS_FILENAME: Duw\n"
        "    TRACK_FILENAME: {name}\n"
        "    DEC_SETUP: \"[:np][:dv hs {head_size}]\"\n"
        "    VOLUME_ADJUST_DB: 0.0\n"
        "    AUTO_NOTE_LEVEL_ENABLED: false\n"
        "    STEM_PEAK_CEILING_DBFS: 0.0\n"
        .format(name=_track_name(head_size), head_size=head_size)
        for head_size in HEAD_SIZES
    )
    path.write_text(
        "# Generated by tools/create_head_size_pitch_reference.py\n"
        "# Raw head-size/pitch loudness reference. Do not add gain correction here.\n"
        "noteOffset: -48\n"
        "minDectalkPitch: 0\n"
        "maxDectalkPitch: 36\n"
        "velocityVolumeScaleDb: 0.0\n"
        "autoNoteLevelEnabled: false\n"
        "stemPeakCeilingDbfs: 0.0\n"
        "\n"
        "Tracks:\n"
        f"{tracks}",
        encoding="ascii",
    )


def create_reference(song_name: str) -> Path:
    song_dir, inputs_dir, lyrics_dir, midi_path = _song_paths(song_name)
    lyrics_dir.mkdir(parents=True, exist_ok=True)
    _write_midi(midi_path)
    _write_lyrics(lyrics_dir / "Duw.txt")
    _write_settings(song_dir / "settings.yaml")
    return song_dir


def _note_name(midi_note: int) -> str:
    names = ("C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B")
    return f"{names[midi_note % 12]}{midi_note // 12 - 1}"


def _measure_window(audio: AudioSegment, start_ms: int, end_ms: int) -> tuple[float | None, float | None]:
    window = audio[start_ms:end_ms]
    if not len(window) or not math.isfinite(window.dBFS):
        return None, None
    peak = window.max_dBFS if math.isfinite(window.max_dBFS) else None
    return window.dBFS, peak


def analyze_reference(song_name: str) -> Path:
    song_dir, _, _, _ = _song_paths(song_name)
    output_dir = song_dir / "outputs"
    analysis_dir = output_dir / "analysis"
    analysis_dir.mkdir(parents=True, exist_ok=True)
    csv_path = analysis_dir / "head_size_pitch_levels.csv"

    rows: list[dict[str, object]] = []
    for head_size in HEAD_SIZES:
        track_name = _track_name(head_size)
        stem_path = output_dir / "_tracks" / f"{track_name}.wav"
        if not stem_path.is_file():
            raise FileNotFoundError(
                f"Missing rendered stem: {stem_path}. Run choir.py {song_name} before analysis."
            )
        audio = AudioSegment.from_file(stem_path)
        for index, midi_note in enumerate(range(FIRST_MIDI_NOTE, FIRST_MIDI_NOTE + NOTE_COUNT)):
            note_start = STEM_LEAD_IN_MS + index * NOTE_DURATION_MS
            dbfs, peak_dbfs = _measure_window(
                audio,
                note_start + ANALYSIS_ATTACK_SKIP_MS,
                note_start + NOTE_DURATION_MS - ANALYSIS_RELEASE_SKIP_MS,
            )
            rows.append(
                {
                    "head_size": head_size,
                    "track": track_name,
                    "note_index": index + 1,
                    "midi_note": midi_note,
                    "scientific_pitch": _note_name(midi_note),
                    "dectalk_pitch": midi_note - FIRST_MIDI_NOTE,
                    "window_start_ms": note_start + ANALYSIS_ATTACK_SKIP_MS,
                    "window_end_ms": note_start + NOTE_DURATION_MS - ANALYSIS_RELEASE_SKIP_MS,
                    "rms_dbfs": "" if dbfs is None else f"{dbfs:.2f}",
                    "peak_dbfs": "" if peak_dbfs is None else f"{peak_dbfs:.2f}",
                }
            )

    with csv_path.open("w", encoding="ascii", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    return csv_path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--song", default=DEFAULT_SONG_NAME, help="song folder to create or analyze")
    parser.add_argument("--analyze", action="store_true", help="measure rendered stems into a CSV instead of creating inputs")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.analyze:
        print(f"Wrote {analyze_reference(args.song)}")
    else:
        print(f"Wrote {create_reference(args.song)}")


if __name__ == "__main__":
    main()
