"""Create a reproducible OCTAVE_BOOST reference song.

The generated song puts the desired final register directly in the MIDI notes.
OCTAVE_BOOST is then used only to move the temporary DECTALK render pitch into a
stable range before the WAV is sped up or slowed down.
"""

from pathlib import Path

from mido import Message, MetaMessage, MidiFile, MidiTrack, bpm2tempo


REPO_ROOT = Path(__file__).resolve().parents[1]
SONG_NAME = 'OctaveBoostReference'
SONG_DIR = REPO_ROOT / 'songs' / SONG_NAME
INPUTS_DIR = SONG_DIR / 'inputs'
LYRICS_DIR = INPUTS_DIR / 'lyrics'
MIDI_PATH = INPUTS_DIR / f'{SONG_NAME}.mid'

TICKS_PER_BEAT = 480
BEATS_PER_CHORD = 4
NOTE_TICKS = TICKS_PER_BEAT * BEATS_PER_CHORD
TEMPO = bpm2tempo(120)


TRACKS = [
	{
		'name': 'OctaveDown1',
		'notes': [36, 45, 41, 43],  # C2, A2, F2, G2
		'octave_boost': -12,
		'head_size': 135,
		'volume_db': -18.0,
	},
	{
		'name': 'Center',
		'notes': [52, 48, 57, 59],  # E3, C3, A3, B3
		'octave_boost': 0,
		'head_size': 110,
		'volume_db': -10.0,
	},
	{
		'name': 'OctaveUp1',
		'notes': [67, 64, 60, 62],  # G4, E4, C4, D4
		'octave_boost': 12,
		'head_size': 95,
		'volume_db': -12.0,
	},
	{
		'name': 'OctaveUp2',
		'notes': [84, 93, 89, 91],  # C6, A6, F6, G6
		'octave_boost': 24,
		'head_size': 80,
		'volume_db': -15.0,
	},
	{
		'name': 'OctaveUp3',
		'notes': [88, 84, 93, 95],  # E6, C6, A6, B6
		'octave_boost': 36,
		'head_size': 80,
		'volume_db': -17.0,
	},
]


SETTINGS_TEMPLATE = """# Generated by tools/create_octave_boost_reference_song.py
# Four-count chord progression: C, Am, F, G.
# MIDI holds the desired final pitches; OCTAVE_BOOST only changes the temporary
# DECTALK render register before speed correction.
noteOffset: -48
minDectalkPitch: 0
maxDectalkPitch: 36

consonantFractionTarget: 0.15
consonantMinMs: 5
consonantMaxMs: 75

# Song-level defaults inherited by every track unless overridden.
# 24 is C5 in this project. The boost is keyed to final audible pitch after
# OCTAVE_BOOST, so high octave reference voices still get the lift.
pitchVolumeBoostStart: 24
pitchVolumeBoostDbPerSemitone: 0.8
pitchVolumeBoostMaxDb: 9.0

# Note normalization is per voice. Auto mode uses the voice's own strong
# upper-C3/lower-C4 register when present, then boosts quieter notes as needed.
noteNormalizeReferenceMin: 7
noteNormalizeReferenceMax: 16
noteNormalizeTargetDbfs: auto
noteNormalizeMaxBoostDb: 9.0
noteNormalizePeakCeilingDbfs: -1.0

Tracks:
{tracks_yaml}
"""


def create_midi():
	midi = MidiFile(ticks_per_beat=TICKS_PER_BEAT)

	for track_def in TRACKS:
		track = MidiTrack()
		midi.tracks.append(track)
		track.append(MetaMessage('track_name', name=track_def['name'], time=0))
		track.append(MetaMessage('set_tempo', tempo=TEMPO, time=0))
		for note in track_def['notes']:
			track.append(Message('note_on', note=note, velocity=96, time=0))
			track.append(Message('note_off', note=note, velocity=0, time=NOTE_TICKS))
		track.append(MetaMessage('end_of_track', time=0))

	midi.save(MIDI_PATH)


def create_lyrics():
	LYRICS_DIR.mkdir(parents=True, exist_ok=True)
	lyrics = '`daa `daa `daa `daa\n'
	(LYRICS_DIR / 'Daa.txt').write_text(lyrics, encoding='ascii')


def create_settings():
	tracks_yaml = []
	for track_def in TRACKS:
		tracks_yaml.append(
			f"  {track_def['name']}:\n"
			"    LYRICS_FILENAME: Daa\n"
			f"    DEC_SETUP: \"[:np][:dv hs {track_def['head_size']}]\"\n"
			f"    VOLUME_ADJUST_DB: {track_def['volume_db']}\n"
			f"    OCTAVE_BOOST: {track_def['octave_boost']}\n"
		)
	(SONG_DIR / 'settings.yaml').write_text(
		SETTINGS_TEMPLATE.format(tracks_yaml=''.join(tracks_yaml)),
		encoding='ascii',
	)


def main():
	SONG_DIR.mkdir(parents=True, exist_ok=True)
	INPUTS_DIR.mkdir(parents=True, exist_ok=True)
	create_midi()
	create_lyrics()
	create_settings()
	print(f'Wrote {SONG_DIR}')


if __name__ == '__main__':
	main()
